(function(){'use strict';
var $=function(id){return document.getElementById(id);},installPrompt=null,online=null,roomCode='',playerId='',playerName='',roomRef=null;
function show(id){$(id).classList.remove('hidden')}function hide(id){$(id).classList.add('hidden')}function status(s){$('onlineStatus').textContent=s}
function isStandalone(){return matchMedia('(display-mode: standalone)').matches||navigator.standalone===true}
function detectDevice(){var mobile=/Android|iPhone|iPad|iPod|Mobile/i.test(navigator.userAgent)||matchMedia('(max-width: 760px)').matches||matchMedia('(pointer: coarse)').matches;document.documentElement.classList.toggle('mobile-ui',mobile);document.documentElement.classList.toggle('standalone',isStandalone());}
function finishSplash(){setTimeout(function(){$('splash').classList.add('fade');setTimeout(function(){$('splash').remove();show('modeScreen')},500)},2500)}
function installSupport(){window.addEventListener('beforeinstallprompt',function(e){e.preventDefault();installPrompt=e;if(!isStandalone())show('installBtn')});$('installBtn').onclick=async function(){if(!installPrompt)return;installPrompt.prompt();await installPrompt.userChoice;installPrompt=null;hide('installBtn')};window.addEventListener('appinstalled',function(){hide('installBtn')});if(/iPhone|iPad|iPod/i.test(navigator.userAgent)&&!isStandalone())show('iosHelp');$('iosHelp').onclick=function(){alert('Safari paylaş düğmesine dokunun, ardından “Ana Ekrana Ekle” seçeneğini seçin.')};if('serviceWorker'in navigator&&location.protocol!=='file:')navigator.serviceWorker.register('./service-worker.js').catch(console.error)}
async function firebase(){if(online)return online;var c=window.PASSAPAROLA_FIREBASE_CONFIG;if(!c||/BURAYA|PROJE_ID/.test(JSON.stringify(c)))throw Error('Firebase ayarları henüz firebase-config.js dosyasına girilmemiş.');var appSdk=await import('https://www.gstatic.com/firebasejs/10.14.1/firebase-app.js'),db=await import('https://www.gstatic.com/firebasejs/10.14.1/firebase-database.js'),authSdk=await import('https://www.gstatic.com/firebasejs/10.14.1/firebase-auth.js'),app=appSdk.initializeApp(c),credential=await authSdk.signInAnonymously(authSdk.getAuth(app));online={db:db.getDatabase(app),api:db,user:credential.user};return online}
function randomCode(){return String(Math.floor(100000+Math.random()*900000))}function randomKey(){return crypto.randomUUID?crypto.randomUUID():Date.now()+'_'+Math.random().toString(36).slice(2)}
async function createRoom(){var pin=prompt('Öğretmen PIN Kodu');if(pin===null)return;var local=PassaparolaStorage.load();if(pin!==String(local.settings.adminPin)){status('Öğretmen PIN kodu hatalı.');return}try{var f=await firebase(),code=randomCode(),ref=f.api.ref(f.db,'rooms/'+code);await f.api.set(ref,{teacherUid:f.user.uid,createdAt:f.api.serverTimestamp(),status:'waiting',settings:local.settings,questions:PassaparolaEngine.activeQuestions(local.questions),players:{}});$('joinCode').value=code;status('Oda oluşturuldu. Katılım kodu: '+code);listenRoom(code);alert('Oda Katılım Kodu: '+code)}catch(e){status(e.message)}}
async function joinRoom(){playerName=$('onlineName').value.trim();roomCode=$('joinCode').value.trim();if(!playerName||!/^[0-9]{6}$/.test(roomCode)){status('Adınızı ve 6 haneli oda kodunu girin.');return}try{var f=await firebase(),snap=await f.api.get(f.api.ref(f.db,'rooms/'+roomCode));if(!snap.exists())throw Error('Oda bulunamadı.');var room=snap.val();playerId=f.user.uid;roomRef=f.api.ref(f.db,'rooms/'+roomCode);await f.api.set(f.api.ref(f.db,'rooms/'+roomCode+'/players/'+playerId),{name:playerName,score:0,correct:0,wrong:0,status:'playing',updatedAt:f.api.serverTimestamp()});f.api.onDisconnect(f.api.ref(f.db,'rooms/'+roomCode+'/players/'+playerId+'/status')).set('disconnected');hide('onlineLobby');show('gameScreen');document.body.insertAdjacentHTML('beforeend','<button id="onlineBadge" class="onlineBadge">ODA '+roomCode+' · CANLI SKOR</button>');$('onlineBadge').onclick=function(){show('liveBoard')};listenRoom(roomCode);if(window.PassaparolaOnlineHooks)window.PassaparolaOnlineHooks.start(room.questions,room.settings,playerName);else throw Error('Oyun modülü hazır değil.')}catch(e){status(e.message)}}
async function syncScore(){if(!roomCode||!playerId||!online)return;var payload={clientKey:sessionStorage.getItem('clientKey'),name:playerName,score:Number($('score').textContent)||0,status:/tamamland|süre doldu/i.test($('modalBody').textContent)?'finished':'playing',updatedAt:online.api.serverTimestamp()};await online.api.update(online.api.ref(online.db,'rooms/'+roomCode+'/players/'+playerId),payload).catch(console.error)}
async function listenRoom(code){var f=await firebase();f.api.onValue(f.api.ref(f.db,'rooms/'+code+'/players'),function(s){var players=Object.values(s.val()||{}).sort(function(a,b){return(b.score||0)-(a.score||0)});$('roomLabel').textContent='Oda: '+code;$('livePlayers').innerHTML=players.map(function(p,i){return'<li><span>'+(i+1)+'. '+escapeHtml(p.name)+'</span><span>'+(p.score||0)+' puan · '+(p.status||'bekliyor')+'</span></li>'}).join('')||'<li>Henüz oyuncu yok.</li>';if(players.some(function(p){return p.status==='finished'}))show('liveBoard')})}
function escapeHtml(s){var d=document.createElement('div');d.textContent=s;return d.innerHTML}
function about(){window.location.href='about.html?v=3'}
document.addEventListener('DOMContentLoaded',function(){detectDevice();addEventListener('resize',detectDevice);finishSplash();installSupport();$('offlineMode').onclick=function(){hide('modeScreen');show('gameScreen')};$('onlineMode').onclick=function(){hide('modeScreen');show('onlineLobby')};$('backModes').onclick=function(){hide('onlineLobby');show('modeScreen')};$('createRoom').onclick=createRoom;$('joinRoom').onclick=joinRoom;$('aboutBtn').onclick=about;$('closeLive').onclick=function(){hide('liveBoard')};new MutationObserver(syncScore).observe($('score'),{childList:true});new MutationObserver(syncScore).observe($('modalBody'),{childList:true,subtree:true})});
})();
document.addEventListener('DOMContentLoaded',function(){var button=document.getElementById('aboutBtn');if(button)button.onclick=function(){window.location.href='about.html?v=3';};});
