(function(g){'use strict';
function active(qs){var seen={};return qs.filter(function(q){var valid=q.enabled===true&&q.question.trim()!==''&&Array.isArray(q.acceptedAnswers)&&q.acceptedAnswers.length>0&&!seen[q.letter];if(valid)seen[q.letter]=true;return valid;}).map(function(q){return JSON.parse(JSON.stringify(q));});}
function Engine(){this.reset();} Engine.prototype.reset=function(){this.questions=[];this.status={};this.queue=[];this.passQueue=[];this.current=null;this.score=0;this.correct=0;this.wrong=0;this.running=false;this.awaitingRestart=false;};
Engine.prototype.start=function(qs){this.reset();this.questions=active(qs);for(var i=0;i<this.questions.length;i++){this.status[this.questions[i].letter]='idle';this.queue.push(this.questions[i]);}this.running=this.queue.length>0;if(this.running)this.next();return this.current;};
Engine.prototype.next=function(){if(!this.running)return null;if(!this.queue.length){this.queue=this.passQueue.splice(0);}if(!this.queue.length){this.running=false;this.current=null;return null;}this.current=this.queue.shift();this.status[this.current.letter]='active';return this.current;};
Engine.prototype.restartRound=function(){if(!this.running||!this.awaitingRestart)return this.current;this.status={};this.queue=[];this.passQueue=[];for(var i=0;i<this.questions.length;i++){this.status[this.questions[i].letter]='idle';this.queue.push(this.questions[i]);}this.current=null;this.score=0;this.correct=0;this.awaitingRestart=false;return this.next();};
Engine.prototype.resolve=function(kind){if(!this.running||!this.current||this.awaitingRestart)return{ended:!this.running};var q=this.current;if(kind==='correct'){this.status[q.letter]='correct';this.score++;this.correct++;}else if(kind==='wrong'){this.status[q.letter]='wrong';this.wrong++;this.awaitingRestart=true;return{ended:false,restart:true,next:null};}else{this.status[q.letter]='passed';this.passQueue.push(q);}this.current=null;var n=this.next();return{ended:!this.running,next:n};};
Engine.prototype.answer=function(value){var norm=function(s){return String(s).trim().replace(/\s+/g,' ').toLocaleLowerCase('tr-TR');};var ok=this.current&&this.current.acceptedAnswers.some(function(a){return norm(a)===norm(value);});var answer=this.current?this.current.acceptedAnswers[0]:'';var result=this.resolve(ok?'correct':'wrong');result.correct=ok;result.answer=answer;return result;};
g.PassaparolaEngine={Engine:Engine,activeQuestions:active};
})(window);
